a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))
print()
print()
print("Addition: ", a+b)
print("Subtraction: ", a-b)
print("Multiplication: ", a*b)
print("Division: ", a/b)
